### ISSUE TITLE
A mistake was made

### ISSUE THREAD

**Issue by ChenArno** [RSATom/WebChimera.js#126]
`Uncaught Error: The module '/Users/century/node/wcjs-ugly-demo-master/node_modules/webchimera.js/WebChimera.js.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 50. This version of Node.js requires
NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/century/node/wcjs-ugly-demo-master/node_modules/webchimera.js/index.js:1:173)
    at Object.<anonymous> (/Users/century/node/wcjs-ugly-demo-master/node_modules/webchimera.js/index.js:3:3)`

**Comment by ChenArno** [comment]
Hi,
when I npm install,and copy webchimera.js in node_modules,it is not working，Was I wrong thanks

**Comment by RSATom** [comment]
> The module '.../WebChimera.js.node' was compiled against a different Node.js
I've forced rebuild on Travis, but don't sure it will help due to #69

**Comment by ChenArno** [comment]
We are using Node.js 7.9.0, Chromium 58.0.3029.110, and Electron 1.7.9.

**Comment by RSATom** [comment]
It looks like prebuild for Mac is broken: https://travis-ci.org/RSATom/WebChimera.js/builds/168941138
So if you still want use it on Mac, you have to build it yourself:
https://github.com/RSATom/WebChimera.js#mac-os-x
https://github.com/RSATom/WebChimera.js#mac-os-x--linux

**Comment by ChenArno** [comment]
Ok,thanks
