### ISSUE TITLE
Help needed after succesfull build

### ISSUE THREAD

**Issue by Ciao121** [RSATom/WebChimera.js#130]
Hi everyone,
I can successfully use prebuilds using wcjs: require('wcjs-prebuilt'). But to use prebuilds I have to use electron 1.4.3 (this is the latest build I can find).

I'm trying to make a build to use with the latest electron version (1.8.3).
I changed set npm_config_wcjs_runtime_version to 1.8.3 and the build successfully completes (no error sor warnings at all).
But when I try to use: wcjs: require('webchimeras.js') I get this error:
```
Uncaught Error: error: 126\\?\C:\Users\ivan\Desktop\Nuov3\playernew\node_modules\webchimera.js\build\Release\WebChimera.js.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at bindings (C:\Users\ivan\Desktop\Nuov3\playernew\node_modules\webchimera.js\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (C:\Users\ivan\Desktop\Nuov3\playernew\node_modules\webchimera.js\index.js:1:192)

```
Tried bot ia32 and x64; the error change from 193(ie32)to 126 (x64)
I need help to solve this :/

Thank you!!!

**Comment by Ciao121** [comment]
Error 193 happens using ia32 on a x64 sysem. So let's use x64. But it show me error 126

**Comment by Ciao121** [comment]
The error seems to say that it cannot find libvlc.dll and libvlccore.dll. Should I put those files manually?

**Comment by Ciao121** [comment]
Problem was https://github.com/RSATom/WebChimera.js/wiki/Latest-Electron-and-NW.js-versions-has-compatibility-issue-on-Windows

**Comment by RSATom** [comment]
Closed as too old.
