### ISSUE TITLE
Uncaught Error: The module 'project/node_modules/webchimera.js/build/Release/WebChimera.js.node'

### ISSUE THREAD

**Issue by echonox** [RSATom/WebChimera.js#131]
when using electron@latest 1.8.4 currently, not mater if i use the prebuilt version, or build it from source, i get this error on mac:

Uncaught Error: The module 'project/node_modules/webchimera.js/build/Release/WebChimera.js.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at bindings

**Comment by RSATom** [comment]
You have to build it yourself for Electron version you have.

**Comment by echonox** [comment]
@RSATom  could you plz give me a direction on how to do it?

**Comment by RSATom** [comment]
https://github.com/RSATom/WebChimera.js#build-prerequisites
https://github.com/RSATom/WebChimera.js#build-from-sources

**Comment by RSATom** [comment]
but keep in mind https://github.com/RSATom/WebChimera.js/issues/69

**Comment by RSATom** [comment]
> was compiled against a different Node.js version using

Means exactly what it says. you have to build `WebChimera.js` for your `Electron` version. And don't forget update target version number inside `build_electron.sh`

**Comment by RSATom** [comment]
No activity. Closed.
