### ISSUE TITLE
Node.js Error: Module version mismatch. Expected 46, got 43.

### ISSUE THREAD

**Issue by skerit** [RSATom/WebChimera.js#62]
I'm trying to use webchimera.js in a node.js app.
Installing it using this command works, everything compiles fine:

    npm install webchimera.js

But requiring chimera in the app results in the following error:

	/media/bridge/projects/develry/cvlc/node_modules/webchimera.js/node_modules/bindings/bindings.js:83
	        throw e
	        ^

	Error: Module version mismatch. Expected 46, got 43.
	    at Error (native)
	    at Object.Module._extensions..node (module.js:460:18)
	    at Module.load (module.js:356:32)
	    at Function.Module._load (module.js:311:12)
	    at Module.require (module.js:366:17)
	    at require (module.js:385:17)
	    at bindings (/media/bridge/projects/develry/cvlc/node_modules/webchimera.js/node_modules/bindings/bindings.js:76:44)
	    at Object.<anonymous> (/media/bridge/projects/develry/cvlc/node_modules/webchimera.js/index.js:1:99)
	    at Module._compile (module.js:435:26)
	    at Object.Module._extensions..js (module.js:442:10)

**Comment by RSATom** [comment]
By default it builds for `nw.js` engine. To use it with `node.js` you have two options:
1. set `npm_config_wcjs_runtime` and `npm_config_wcjs_runtime_version` env variables before `npm install` ( like [here](https://github.com/RSATom/WebChimera.js/blob/master/build_node.sh) )
2. add 
```
  "cmake-js": {
    "runtime": "node",
    "runtimeVersion": "0.12.7"
  }
```
to your ` package.json` ( [docs](https://github.com/cmake-js/cmake-js#runtimes) )

**Comment by RSATom** [comment]
Did you get it working? Can we close this issue?

**Comment by RSATom** [comment]
Assume it solved. if not - reopen please.
